### GET Transactions
GET http://localhost:5204/api/pos/transactions
Accept: application/json

### GET Transactions With Filter
GET http://localhost:5204/api/pos/transactions?quantity=10&page=1&size=50
Accept: application/json

### POST Transaction
POST http://localhost:5204/api/pos/transactions
Accept: application/json
Content-Type: application/json

{
  "Item": "c3fc08a1-91f3-43db-a160-0fc46e1cc36b",
  "Quantity": 10,
  "Category": 1,
  "Price": 100000.00
}
