### GET Transactions
GET http://localhost:5204/api/pos/transactions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJVc2VybmFtZSAxIiwianRpIjoiYjc3NjhkMWUtYjkwNy00MTdjLWIxZWEtOWZiYjMzNDM2MDZkIiwiZXhwIjoxNzMzMDU1MDYxLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAifQ.S8qfnmjBFKyzh11l8JpIvSKzJzJPxUIve-W_gJ4Yeb4
Accept: application/json

### GET Transactions With Filter
GET http://localhost:5204/api/pos/transactions?quantity=10&page=1&size=50
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJVc2VybmFtZSAxIiwianRpIjoiYjc3NjhkMWUtYjkwNy00MTdjLWIxZWEtOWZiYjMzNDM2MDZkIiwiZXhwIjoxNzMzMDU1MDYxLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAifQ.S8qfnmjBFKyzh11l8JpIvSKzJzJPxUIve-W_gJ4Yeb4
Accept: application/json

### POST Transaction
POST http://localhost:5204/api/pos/transactions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJVc2VybmFtZSAxIiwianRpIjoiYjc3NjhkMWUtYjkwNy00MTdjLWIxZWEtOWZiYjMzNDM2MDZkIiwiZXhwIjoxNzMzMDU1MDYxLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAifQ.S8qfnmjBFKyzh11l8JpIvSKzJzJPxUIve-W_gJ4Yeb4
Accept: application/json
Content-Type: application/json

{
  "Item": "c3fc08a1-91f3-43db-a160-0fc46e1cc36b",
  "Quantity": 10,
  "Category": 1,
  "Price": 100000.00
}
